"""init postgres schema

Revision ID: 3d0d31e433ce
Revises: 
Create Date: 2026-02-18 15:05:52.988303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d0d31e433ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_postes')),
    sa.UniqueConstraint('nom', name=op.f('uq_postes_nom'))
    )
    op.create_table('regimes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('min_rp_annuels', sa.Integer(), nullable=True),
    sa.Column('min_rp_dimanches', sa.Integer(), nullable=True),
    sa.Column('min_rpsd', sa.Integer(), nullable=True),
    sa.Column('min_rp_2plus', sa.Integer(), nullable=True),
    sa.Column('min_rp_semestre', sa.Integer(), nullable=True),
    sa.Column('avg_service_minutes', sa.Integer(), nullable=True),
    sa.Column('avg_tolerance_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regimes')),
    sa.UniqueConstraint('nom', name=op.f('uq_regimes_nom'))
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('name', name=op.f('uq_teams_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('code_personnel', sa.String(length=50), nullable=True),
    sa.Column('regime_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['regime_id'], ['regimes.id'], name=op.f('fk_agents_regime_id_regimes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index('ix_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('tranches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=False),
    sa.Column('heure_fin', sa.Time(), nullable=False),
    sa.Column('poste_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['poste_id'], ['postes.id'], name=op.f('fk_tranches_poste_id_postes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tranches')),
    sa.UniqueConstraint('nom', 'poste_id', name='_tranche_unique_per_poste'),
    sa.UniqueConstraint('poste_id', 'id', name='uq_tranche_poste_id_id')
    )
    op.create_table('agent_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('day_date', sa.Date(), nullable=False),
    sa.Column('day_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_off_shift', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_days_agent_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_days')),
    sa.UniqueConstraint('agent_id', 'day_date', name='uq_agent_days_agent_date')
    )
    op.create_table('agent_teams',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_teams_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_agent_teams_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'team_id', name=op.f('pk_agent_teams'))
    )
    op.create_index('ix_agent_teams_agent_id', 'agent_teams', ['agent_id'], unique=False)
    op.create_index('ix_agent_teams_team_id', 'agent_teams', ['team_id'], unique=False)
    op.create_table('poste_coverage_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('poste_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('tranche_id', sa.Integer(), nullable=False),
    sa.Column('required_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('weekday >= 0 AND weekday <= 6', name=op.f('ck_poste_coverage_requirements_ck_poste_coverage_weekday_range')),
    sa.ForeignKeyConstraint(['poste_id', 'tranche_id'], ['tranches.poste_id', 'tranches.id'], name='fk_pcr_poste_tranche', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poste_id'], ['postes.id'], name=op.f('fk_poste_coverage_requirements_poste_id_postes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poste_coverage_requirements')),
    sa.UniqueConstraint('poste_id', 'weekday', 'tranche_id', name='uq_poste_weekday_tranche')
    )
    op.create_index('ix_poste_coverage_poste_weekday', 'poste_coverage_requirements', ['poste_id', 'weekday'], unique=False)
    op.create_index(op.f('ix_poste_coverage_requirements_poste_id'), 'poste_coverage_requirements', ['poste_id'], unique=False)
    op.create_index(op.f('ix_poste_coverage_requirements_tranche_id'), 'poste_coverage_requirements', ['tranche_id'], unique=False)
    op.create_table('qualifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('poste_id', sa.Integer(), nullable=False),
    sa.Column('date_qualification', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_qualifications_agent_id_agents')),
    sa.ForeignKeyConstraint(['poste_id'], ['postes.id'], name=op.f('fk_qualifications_poste_id_postes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qualifications')),
    sa.UniqueConstraint('agent_id', 'poste_id', name='_qualification_uc')
    )
    op.create_table('agent_day_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_day_id', sa.Integer(), nullable=False),
    sa.Column('tranche_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_day_id'], ['agent_days.id'], name=op.f('fk_agent_day_assignments_agent_day_id_agent_days'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tranche_id'], ['tranches.id'], name=op.f('fk_agent_day_assignments_tranche_id_tranches'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_day_assignments')),
    sa.UniqueConstraint('agent_day_id', 'tranche_id', name='uq_agent_day_assignments_day_tranche')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_day_assignments')
    op.drop_table('qualifications')
    op.drop_index(op.f('ix_poste_coverage_requirements_tranche_id'), table_name='poste_coverage_requirements')
    op.drop_index(op.f('ix_poste_coverage_requirements_poste_id'), table_name='poste_coverage_requirements')
    op.drop_index('ix_poste_coverage_poste_weekday', table_name='poste_coverage_requirements')
    op.drop_table('poste_coverage_requirements')
    op.drop_index('ix_agent_teams_team_id', table_name='agent_teams')
    op.drop_index('ix_agent_teams_agent_id', table_name='agent_teams')
    op.drop_table('agent_teams')
    op.drop_table('agent_days')
    op.drop_table('tranches')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('agents')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('regimes')
    op.drop_table('postes')
    # ### end Alembic commands ###
