"""feat(regime): add rh constraints fields

Revision ID: 42605377b4f0
Revises: e6d13b6c0271
Create Date: 2026-01-19 09:47:49.581140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42605377b4f0'
down_revision: Union[str, Sequence[str], None] = 'e6d13b6c0271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regimes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_rp_annuels', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('min_rp_dimanches', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('min_rpsd', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('min_rp_2plus', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('min_rp_semestre', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('avg_service_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('avg_tolerance_minutes', sa.Integer(), nullable=True))
        batch_op.drop_column('duree_moyenne_journee_service_min')
        batch_op.drop_column('repos_periodiques_annuels')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regimes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repos_periodiques_annuels', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('duree_moyenne_journee_service_min', sa.INTEGER(), nullable=False))
        batch_op.drop_column('avg_tolerance_minutes')
        batch_op.drop_column('avg_service_minutes')
        batch_op.drop_column('min_rp_semestre')
        batch_op.drop_column('min_rp_2plus')
        batch_op.drop_column('min_rpsd')
        batch_op.drop_column('min_rp_dimanches')
        batch_op.drop_column('min_rp_annuels')

    # ### end Alembic commands ###
