"""add solver_options to planning_drafts

Revision ID: 5fc5e82706d6
Revises: b91d2e46f031
Create Date: 2026-03-03 16:34:06.630073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc5e82706d6'
down_revision: Union[str, Sequence[str], None] = 'b91d2e46f031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planning_drafts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solver_options', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planning_drafts', schema=None) as batch_op:
        batch_op.drop_column('solver_options')

    # ### end Alembic commands ###
