"""drop affectation and etat_jour_agent tables

Revision ID: 856677b677e4
Revises: 94ec304ebf0a
Create Date: 2026-01-27 13:25:12.805892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '856677b677e4'
down_revision: Union[str, Sequence[str], None] = '94ec304ebf0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etat_jour_agent')
    op.drop_table('affectations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affectations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agent_id', sa.INTEGER(), nullable=False),
    sa.Column('tranche_id', sa.INTEGER(), nullable=False),
    sa.Column('jour', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_affectations_agent_id_agents')),
    sa.ForeignKeyConstraint(['tranche_id'], ['tranches.id'], name=op.f('fk_affectations_tranche_id_tranches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_affectations')),
    sa.UniqueConstraint('agent_id', 'jour', 'tranche_id', name=op.f('_affectation_uc'))
    )
    op.create_table('etat_jour_agent',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agent_id', sa.INTEGER(), nullable=False),
    sa.Column('jour', sa.DATE(), nullable=False),
    sa.Column('type_jour', sa.VARCHAR(length=7), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_etat_jour_agent_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_etat_jour_agent')),
    sa.UniqueConstraint('agent_id', 'jour', name=op.f('_etat_jour_uc'))
    )
    # ### end Alembic commands ###
