"""add teams and agent_teams tables

Revision ID: 94ec304ebf0a
Revises: 42605377b4f0
Create Date: 2026-01-26 16:35:46.149561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94ec304ebf0a'
down_revision: Union[str, Sequence[str], None] = '42605377b4f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('name', name=op.f('uq_teams_name'))
    )
    op.create_table('agent_teams',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_teams_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_agent_teams_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'team_id', name=op.f('pk_agent_teams'))
    )
    with op.batch_alter_table('agent_teams', schema=None) as batch_op:
        batch_op.create_index('ix_agent_teams_agent_id', ['agent_id'], unique=False)
        batch_op.create_index('ix_agent_teams_team_id', ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_teams', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_teams_team_id')
        batch_op.drop_index('ix_agent_teams_agent_id')

    op.drop_table('agent_teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
