"""add poste coverage requirements

Revision ID: ce65695fb1c5
Revises: 856677b677e4
Create Date: 2026-01-29 10:24:50.198959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce65695fb1c5'
down_revision: Union[str, Sequence[str], None] = '856677b677e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poste_coverage_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poste_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('tranche_id', sa.Integer(), nullable=False),
    sa.Column('required_count', sa.Integer(), nullable=False, server_default=sa.text("1")),
    sa.ForeignKeyConstraint(['poste_id', 'tranche_id'], ['tranches.poste_id', 'tranches.id'], name='fk_pcr_poste_tranche', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poste_id'], ['postes.id'], name=op.f('fk_poste_coverage_requirements_poste_id_postes'), ondelete='CASCADE'),
    sa.CheckConstraint("weekday >= 0 AND weekday <= 6", name="ck_poste_coverage_weekday_range"),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poste_coverage_requirements')),
    sa.UniqueConstraint('poste_id', 'weekday', 'tranche_id', name='uq_poste_weekday_tranche')
    )
    with op.batch_alter_table('poste_coverage_requirements', schema=None) as batch_op:
        batch_op.create_index('ix_poste_coverage_poste_weekday', ['poste_id', 'weekday'], unique=False)
        batch_op.create_index(batch_op.f('ix_poste_coverage_requirements_tranche_id'), ['tranche_id'], unique=False)

    with op.batch_alter_table('tranches', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_tranche_poste_id_id', ['poste_id', 'id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tranches', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tranche_poste_id_id', type_='unique')

    with op.batch_alter_table('poste_coverage_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poste_coverage_requirements_tranche_id'))
        batch_op.drop_index('ix_poste_coverage_poste_weekday')

    op.drop_table('poste_coverage_requirements')
    # ### end Alembic commands ###
