"""add agent_days and agent_day_assignments tables

Revision ID: e6d13b6c0271
Revises: 183407c44426
Create Date: 2025-12-30 16:13:21.971585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6d13b6c0271'
down_revision: Union[str, Sequence[str], None] = '183407c44426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('day_date', sa.Date(), nullable=False),
    sa.Column('day_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_off_shift', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_days_agent_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_days')),
    sa.UniqueConstraint('agent_id', 'day_date', name='uq_agent_days_agent_date')
    )
    op.create_table('agent_day_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_day_id', sa.Integer(), nullable=False),
    sa.Column('tranche_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_day_id'], ['agent_days.id'], name=op.f('fk_agent_day_assignments_agent_day_id_agent_days'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tranche_id'], ['tranches.id'], name=op.f('fk_agent_day_assignments_tranche_id_tranches'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_day_assignments')),
    sa.UniqueConstraint('agent_day_id', 'tranche_id', name='uq_agent_day_assignments_day_tranche')
    )
    # ### end Alembic commands ###

    op.create_index("ix_agent_days_agent_id", "agent_days", ["agent_id"])
    op.create_index("ix_agent_days_day_date", "agent_days", ["day_date"])
    op.create_index("ix_agent_day_assignments_agent_day_id", "agent_day_assignments", ["agent_day_id"])
    op.create_index("ix_agent_day_assignments_tranche_id", "agent_day_assignments", ["tranche_id"])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_agent_day_assignments_tranche_id", table_name="agent_day_assignments")
    op.drop_index("ix_agent_day_assignments_agent_day_id", table_name="agent_day_assignments")
    op.drop_index("ix_agent_days_day_date", table_name="agent_days")
    op.drop_index("ix_agent_days_agent_id", table_name="agent_days")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_day_assignments')
    op.drop_table('agent_days')
    # ### end Alembic commands ###
