"use client";

import * as React from "react";
import { toast } from "sonner";

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetClose, SheetContent, SheetTitle } from "@/components/ui/sheet";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

import { ApiError } from "@/lib/api/errors";

import { DebugStatsCard } from "./DebugStatsCard";
import type { PlanningGenerateHistoryItem } from "../hooks/usePlanningGenerateHistory";
import type {
  JobStatus,
  PlanningGenerateJobStatusResponse,
  PlanningGenerateRequest,
} from "../hooks/useTeamPlanningGenerate";

type TeamAutoGenerateDebugSheetProps = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  selectionMode: "job" | "draft";
  jobId: string | null;
  draftId: number | null;
  status: JobStatus | null;
  jobData?: PlanningGenerateJobStatusResponse;
  jobError?: Error;
  draftError?: Error;
  draftNotFound: boolean;
  showConflictAlert: boolean;
  requestPayload: PlanningGenerateRequest | null;
  history: PlanningGenerateHistoryItem[];
  jobSelectValue: string;
  draftSelectValue: string;
  onSelectJob: (value: string) => Promise<void>;
  onSelectDraft: (value: string) => Promise<void>;
  onRefreshStatus: () => void;
  onReset: () => void;
  onClearHistory: () => void;
};

function formatErrorMessage(error: unknown) {
  if (!error) return "Erreur inconnue";
  if (typeof error === "string") return error;
  return JSON.stringify(error, null, 2);
}

export function TeamAutoGenerateDebugSheet({
  open,
  onOpenChange,
  selectionMode,
  jobId,
  draftId,
  status,
  jobData,
  jobError,
  draftError,
  draftNotFound,
  showConflictAlert,
  requestPayload,
  history,
  jobSelectValue,
  draftSelectValue,
  onSelectJob,
  onSelectDraft,
  onRefreshStatus,
  onReset,
  onClearHistory,
}: TeamAutoGenerateDebugSheetProps) {
  const copyJson = React.useCallback(async (label: string, value: unknown) => {
    try {
      if (typeof navigator === "undefined" || !navigator.clipboard) {
        throw new Error("Clipboard indisponible");
      }
      await navigator.clipboard.writeText(JSON.stringify(value, null, 2));
      toast.success(`${label} copié`);
    } catch {
      toast.error(`Erreur copie ${label}`);
    }
  }, []);

  const historyItem = React.useMemo(() => {
    if (jobId) return history.find((item) => item.job_id === jobId) ?? null;
    if (draftId != null) return history.find((item) => item.draft_id === draftId) ?? null;
    return null;
  }, [history, jobId, draftId]);

  const hasDraftError404 = draftError instanceof ApiError && draftError.status === 404;
  const hasError =
    showConflictAlert ||
    draftNotFound ||
    hasDraftError404 ||
    status === "failed" ||
    Boolean(jobError?.message) ||
    Boolean(draftError?.message);
  const statsReady = status === "success" && Boolean(jobData?.result_stats);
  const historyCount = history.length;

  const errorPayload = React.useMemo(
    () => ({
      generate_conflict_409: showConflictAlert,
      job_error: jobError?.message ?? null,
      job_failed_error: jobData?.error ?? null,
      solver_status: jobData?.solver_status ?? null,
      draft_not_found_404: draftNotFound,
      draft_error: draftError?.message ?? null,
      draft_error_is_404: hasDraftError404,
    }),
    [showConflictAlert, jobError, jobData?.error, jobData?.solver_status, draftNotFound, draftError, hasDraftError404],
  );

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent side="bottom" className="h-[70vh] rounded-t-2xl p-0">
        <Tabs defaultValue="status" className="h-full gap-0">
          <div className="bg-background sticky top-0 z-10 space-y-3 border-b p-4">
            <div className="flex items-center justify-between">
              <SheetTitle>Debug</SheetTitle>
              <SheetClose asChild>
                <Button variant="ghost" size="sm">
                  Close
                </Button>
              </SheetClose>
            </div>
            <TabsList>
              <TabsTrigger value="status">Status</TabsTrigger>
              <TabsTrigger value="stats" className="gap-2">
                Stats
                {statsReady ? (
                  <Badge variant="secondary" className="h-5 px-1.5 text-[10px] leading-none">
                    OK
                  </Badge>
                ) : null}
              </TabsTrigger>
              <TabsTrigger value="errors" className="gap-2">
                Errors
                {hasError ? (
                  <Badge variant="destructive" className="h-5 px-1.5 text-[10px] leading-none">
                    !
                  </Badge>
                ) : null}
              </TabsTrigger>
              <TabsTrigger value="history" className="gap-2">
                History
                {historyCount > 0 ? (
                  <Badge variant="secondary" className="h-5 px-1.5 text-[10px] leading-none">
                    {historyCount}
                  </Badge>
                ) : null}
              </TabsTrigger>
            </TabsList>
          </div>

          <div className="min-h-0 flex-1">
            <TabsContent value="status" className="h-full">
              <ScrollArea className="h-full p-4">
                <div className="space-y-3 pb-4">
                  <p className="text-sm">Mode: {selectionMode === "job" ? "Job actif" : "Draft sélectionné"}</p>
                  <p className="text-xs text-muted-foreground">job_id: {jobId ?? "—"}</p>
                  <p className="text-xs text-muted-foreground">draft_id: {draftId ?? "—"}</p>
                  <p className="text-xs text-muted-foreground">status: {status ?? "—"}</p>

                  <div className="rounded-md border p-3 text-xs">
                    <p>team_id: {requestPayload?.team_id ?? "—"}</p>
                    <p>start_date: {requestPayload?.start_date ?? "—"}</p>
                    <p>end_date: {requestPayload?.end_date ?? "—"}</p>
                    <p>seed: {requestPayload?.seed ?? "—"}</p>
                    <p>time_limit_seconds: {requestPayload?.time_limit_seconds ?? "—"}</p>
                  </div>

                  <div className="rounded-md border p-3 text-xs">
                    <p>created_at: {historyItem?.created_at ?? "—"}</p>
                    <p>updated_at: {historyItem?.updated_at ?? "—"}</p>
                    <p>last_seen_at: {historyItem?.last_seen_at ?? "—"}</p>
                  </div>

                  <div className="flex flex-wrap gap-2">
                    <Button variant="outline" size="sm" onClick={onRefreshStatus} disabled={!jobId}>
                      Rafraîchir statut
                    </Button>
                    <Button variant="outline" size="sm" onClick={onReset}>
                      Réinitialiser
                    </Button>
                    <Button variant="outline" size="sm" onClick={() => void copyJson("job response", jobData)}>
                      Copier job response
                    </Button>
                    <Button variant="outline" size="sm" onClick={() => void copyJson("request", requestPayload)}>
                      Copier request
                    </Button>
                  </div>
                </div>
              </ScrollArea>
            </TabsContent>

            <TabsContent value="stats" className="h-full">
              <ScrollArea className="h-full p-4">
                <div className="space-y-4 pb-4">
                  <DebugStatsCard data={jobData} />
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => void copyJson("result_stats", jobData?.result_stats ?? null)}
                  >
                    Copier JSON result_stats
                  </Button>
                </div>
              </ScrollArea>
            </TabsContent>

            <TabsContent value="errors" className="h-full">
              <ScrollArea className="h-full p-4">
                <div className="space-y-3 pb-4">
                  {showConflictAlert ? (
                    <Alert>
                      <AlertTitle>POST /generate: 409</AlertTitle>
                      <AlertDescription>Une génération est déjà en cours.</AlertDescription>
                    </Alert>
                  ) : null}

                  {jobData?.status === "failed" ? (
                    <Alert variant="destructive">
                      <AlertTitle>Job failed</AlertTitle>
                      <AlertDescription>
                        <p>{formatErrorMessage(jobData.error)}</p>
                        {jobData.solver_status ? <p>solver_status: {jobData.solver_status}</p> : null}
                      </AlertDescription>
                    </Alert>
                  ) : null}

                  {draftNotFound ? (
                    <Alert variant="destructive">
                      <AlertTitle>Draft 404</AlertTitle>
                      <AlertDescription>Draft introuvable (supprimé / non créé).</AlertDescription>
                    </Alert>
                  ) : null}

                  <div className="space-y-2">
                    <div className="flex justify-end">
                      <Button variant="outline" size="sm" onClick={() => void copyJson("errors payload", errorPayload)}>
                        Copier
                      </Button>
                    </div>
                    <ScrollArea className="h-64 rounded-md border bg-muted/30 p-2">
                      <pre className="font-mono text-xs">{JSON.stringify(errorPayload, null, 2)}</pre>
                    </ScrollArea>
                  </div>
                </div>
              </ScrollArea>
            </TabsContent>

            <TabsContent value="history" className="h-full">
              <ScrollArea className="h-full p-4">
                <div className="space-y-3 pb-4">
                  <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                    <div className="space-y-2">
                      <p className="text-sm font-medium">Recharger un job</p>
                      <Select value={jobSelectValue} onValueChange={(value) => void onSelectJob(value)}>
                        <SelectTrigger>
                          <SelectValue placeholder="Sélectionner un job_id" />
                        </SelectTrigger>
                        <SelectContent>
                          {history.map((item) => (
                            <SelectItem key={item.job_id} value={item.job_id}>
                              {item.job_id} ({item.status_last_known})
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>

                    <div className="space-y-2">
                      <p className="text-sm font-medium">Afficher un draft</p>
                      <Select value={draftSelectValue} onValueChange={(value) => void onSelectDraft(value)}>
                        <SelectTrigger>
                          <SelectValue placeholder="Sélectionner un draft_id" />
                        </SelectTrigger>
                        <SelectContent>
                          {history
                            .filter((item) => item.draft_id)
                            .map((item) => (
                              <SelectItem key={`${item.job_id}-${item.draft_id}`} value={String(item.draft_id)}>
                                Draft #{item.draft_id} (job {item.job_id.slice(0, 8)}…)
                              </SelectItem>
                            ))}
                        </SelectContent>
                      </Select>
                    </div>
                  </div>

                  <div className="flex flex-wrap gap-2">
                    <Button variant="outline" size="sm" onClick={onReset}>
                      Réinitialiser
                    </Button>
                    <Button variant="outline" size="sm" onClick={onClearHistory}>
                      Vider historique
                    </Button>
                    <Button variant="outline" size="sm" onClick={() => void copyJson("history", history)}>
                      Copier history
                    </Button>
                  </div>
                </div>
              </ScrollArea>
            </TabsContent>
          </div>
        </Tabs>
      </SheetContent>
    </Sheet>
  );
}
