"use client";

import * as React from "react";
import { endOfMonth, startOfMonth } from "date-fns";
import { Loader2 } from "lucide-react";
import { toast } from "sonner";

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

import { ApiError } from "@/lib/api/errors";
import type { Team } from "@/types";
import { toISODate } from "@/utils/date.format";
import { PlanningPeriodControls } from "@/features/planning-common/period/PlanningPeriodControls";
import type { PlanningPeriod } from "@/features/planning-common/period/period.types";
import { shiftPlanningPeriod } from "@/features/planning-common/period/period.utils";
import { TeamHeaderSelect } from "@/features/planning-team/components/TeamHeaderSelect";
import { TeamPlanningMatrix } from "@/features/planning-team/components/TeamPlanningMatrix";
import { buildTeamPlanningVm } from "@/features/planning-team/vm/teamPlanning.vm.builder";

import { TeamAutoGenerateDebugSheet } from "./TeamAutoGenerateDebugSheet";
import { JobStatusBar, type DebugIndicator, type DebugTab } from "./JobStatusBar";
import { usePlanningGenerateHistory } from "../hooks/usePlanningGenerateHistory";
import {
  useTeamPlanningGenerate,
  type PlanningGenerateRequest,
} from "../hooks/useTeamPlanningGenerate";
import { useTeamPlanningDraft } from "../hooks/useTeamPlanningDraft";
import { useTeamPlanningGenerateJob } from "../hooks/useTeamPlanningGenerateJob";

/**
 * Debug UI is hidden by default in production.
 * Set NEXT_PUBLIC_PLANNING_DEBUG=1 to enable explicitly.
 */
const DEBUG_ENABLED =
  process.env.NEXT_PUBLIC_PLANNING_DEBUG === "1" || process.env.NODE_ENV !== "production";

type SelectionMode = "job" | "draft";

function buildErrorFingerprint(error: unknown): string {
  if (!error) return "none";
  if (typeof error === "string") return `${error.slice(0, 200)}:${error.length}`;

  try {
    return JSON.stringify(error).slice(0, 200);
  } catch {
    return "unserializable";
  }
}

export function TeamAutoGeneratePage({ teams }: { teams: Team[] }) {
  const [teamId, setTeamId] = React.useState<number | null>(null);
  const [seed, setSeed] = React.useState(0);
  const [timeLimitSeconds, setTimeLimitSeconds] = React.useState(60);

  const [period, setPeriod] = React.useState<PlanningPeriod>({
    kind: "month",
    month: startOfMonth(new Date()),
  });

  const [jobId, setJobId] = React.useState<string | null>(null);
  const [draftId, setDraftId] = React.useState<number | null>(null);
  const [selectionMode, setSelectionMode] = React.useState<SelectionMode>("job");
  const [showConflictAlert, setShowConflictAlert] = React.useState(false);
  const [draftNotFound, setDraftNotFound] = React.useState(false);
  const [isSubmittingLocal, setIsSubmittingLocal] = React.useState(false);
  const [isDebugOpen, setIsDebugOpen] = React.useState(false);
  const [activeDebugTab, setActiveDebugTab] = React.useState<DebugTab>("status");
  const [lastRequestPayload, setLastRequestPayload] = React.useState<PlanningGenerateRequest | null>(null);
  const [jobStartedAtMs, setJobStartedAtMs] = React.useState<number | null>(null);
  const [jobFinishedAtMs, setJobFinishedAtMs] = React.useState<number | null>(null);

  const submitTokenRef = React.useRef(0);
  const planningSectionRef = React.useRef<HTMLDivElement | null>(null);
  const lastAutoOpenKeyRef = React.useRef<string | null>(null);

  const {
    history,
    lastJobId,
    setLastJobId,
    upsertFromGenerateResponse,
    updateStatus,
    select,
    selectDraft,
    clear,
  } = usePlanningGenerateHistory();

  const range = React.useMemo(() => {
    if (period.kind === "month") {
      return {
        startDate: toISODate(startOfMonth(period.month)),
        endDate: toISODate(endOfMonth(period.month)),
      };
    }

    return {
      startDate: toISODate(period.start),
      endDate: toISODate(period.end),
    };
  }, [period]);

  const generate = useTeamPlanningGenerate();
  const job = useTeamPlanningGenerateJob(jobId);
  const draft = useTeamPlanningDraft(draftId);

  const isPeriodInvalid = range.startDate > range.endDate;
  const status = job.data?.status ?? null;
  const isRunning = status === "queued" || status === "running";
  const isBusy = generate.isSubmitting || isSubmittingLocal || isRunning;
  const canGenerate = teamId !== null && !isPeriodInvalid && !isBusy;
  const hasError = status === "failed" || showConflictAlert || draftNotFound;
  const shouldShowStatusBar = Boolean(jobId || status || draftId);
  const successHasStats = status === "success" && Boolean(job.data?.result_stats);

  const debugIndicator = React.useMemo<DebugIndicator>(() => {
    if (hasError) return "error";
    if (successHasStats) return "success";
    if (isRunning) return "busy";
    return "none";
  }, [hasError, successHasStats, isRunning]);

  const jobSelectValue = jobId ?? "";
  const draftSelectValue = draftId != null ? String(draftId) : "";

  const currentErrorKey = React.useMemo(() => {
    if (showConflictAlert) {
      const conflictTeamId = lastRequestPayload?.team_id ?? teamId ?? "none";
      const conflictStart = lastRequestPayload?.start_date ?? range.startDate;
      const conflictEnd = lastRequestPayload?.end_date ?? range.endDate;
      return `409:${jobId ?? "none"}:${conflictTeamId}:${conflictStart}:${conflictEnd}`;
    }

    if (draftNotFound) {
      return `draft404:${draftId ?? "none"}:${jobId ?? "none"}`;
    }

    if (job.data?.status === "failed") {
      const errorFingerprint = buildErrorFingerprint(job.data.error);
      return `failed:${jobId ?? "none"}:${errorFingerprint}`;
    }

    return null;
  }, [
    showConflictAlert,
    lastRequestPayload?.team_id,
    lastRequestPayload?.start_date,
    lastRequestPayload?.end_date,
    teamId,
    range.startDate,
    range.endDate,
    draftNotFound,
    draftId,
    jobId,
    job.data?.status,
    job.data?.error,
  ]);

  React.useEffect(() => {
    if (jobId || !lastJobId) return;
    setJobId(lastJobId);
    if (selectionMode !== "job") setSelectionMode("job");
  }, [jobId, lastJobId, selectionMode]);

  React.useEffect(() => {
    if (!jobId || !job.data) return;

    updateStatus(jobId, job.data.status, job.data.draft_id);

    if (job.data.status === "success" && job.data.draft_id) {
      if (draftId !== job.data.draft_id) setDraftId(job.data.draft_id);
      if (draftNotFound) setDraftNotFound(false);
      if (selectionMode !== "job") setSelectionMode("job");
    }
  }, [jobId, job.data, updateStatus, draftId, draftNotFound, selectionMode]);

  React.useEffect(() => {
    const isDraft404 = draft.error instanceof ApiError && draft.error.status === 404;
    if (draftNotFound !== isDraft404) setDraftNotFound(isDraft404);
  }, [draft.error, draftNotFound]);

  React.useEffect(() => {
    if (currentErrorKey !== null) return;
    lastAutoOpenKeyRef.current = null;
  }, [currentErrorKey]);

  React.useEffect(() => {
    if (jobId) return;

    if (jobStartedAtMs !== null) setJobStartedAtMs(null);
    if (jobFinishedAtMs !== null) setJobFinishedAtMs(null);
  }, [jobFinishedAtMs, jobId, jobStartedAtMs]);

  React.useEffect(() => {
    if (!jobId || !status) return;

    if ((status === "queued" || status === "running") && jobStartedAtMs === null) {
      setJobStartedAtMs(Date.now());
      if (jobFinishedAtMs !== null) setJobFinishedAtMs(null);
      return;
    }

    if (status !== "success" && status !== "failed") return;

    if (jobStartedAtMs === null) {
      const now = Date.now();
      setJobStartedAtMs(now);
      setJobFinishedAtMs(now);
      return;
    }

    if (jobFinishedAtMs === null) {
      setJobFinishedAtMs(Date.now());
    }
  }, [jobFinishedAtMs, jobId, jobStartedAtMs, status]);

  const planningVm = React.useMemo(() => {
    if (!draft.data) return null;
    return buildTeamPlanningVm(draft.data);
  }, [draft.data]);

  const resetViewState = React.useCallback(() => {
    if (showConflictAlert) setShowConflictAlert(false);
    if (draftNotFound) setDraftNotFound(false);
  }, [showConflictAlert, draftNotFound]);

  const clearSWRLocalViews = React.useCallback(async () => {
    await Promise.all([job.clearJobCache(), draft.clearDraftCache()]);
  }, [job, draft]);

  const handleGenerate = React.useCallback(async () => {
    if (!canGenerate || teamId === null || isSubmittingLocal) return;

    setIsSubmittingLocal(true);
    resetViewState();

    const submitToken = submitTokenRef.current + 1;
    submitTokenRef.current = submitToken;

    const payload: PlanningGenerateRequest = {
      team_id: teamId,
      start_date: range.startDate,
      end_date: range.endDate,
      seed,
      time_limit_seconds: timeLimitSeconds,
    };
    setLastRequestPayload(payload);

    try {
      const response = await generate.submit(payload);
      if (submitToken !== submitTokenRef.current) return;

      setJobId(response.job_id);
      setSelectionMode("job");
      setLastJobId(response.job_id);
      setDraftId(response.draft_id ?? null);
      const now = Date.now();
      setJobStartedAtMs(now);
      setJobFinishedAtMs(null);
      upsertFromGenerateResponse(response, payload);
    } catch (error) {
      if (submitToken !== submitTokenRef.current) return;

      if (error instanceof ApiError && error.status === 409) {
        setShowConflictAlert(true);

        if (jobId) {
          setLastJobId(jobId);
          await job.mutate();
          return;
        }

        if (lastJobId) {
          setJobId(lastJobId);
          setSelectionMode("job");
          await job.mutate();
        }
      }
    } finally {
      if (submitToken === submitTokenRef.current) {
        setIsSubmittingLocal(false);
      }
    }
  }, [
    canGenerate,
    teamId,
    isSubmittingLocal,
    resetViewState,
    range.startDate,
    range.endDate,
    seed,
    timeLimitSeconds,
    generate,
    setLastJobId,
    upsertFromGenerateResponse,
    jobId,
    lastJobId,
    job,
  ]);

  const onSelectJob = React.useCallback(
    async (value: string) => {
      if (!value || value === jobId) return;

      resetViewState();
      if (selectionMode !== "job") setSelectionMode("job");
      if (draftId !== null) setDraftId(null);
      await clearSWRLocalViews();

      setJobId(value);
      setLastJobId(value);

      const selected = select(value);
      if (selected?.draft_id && selected.draft_id !== draftId) {
        setDraftId(selected.draft_id);
      }

      if (selected?.status_last_known === "queued" || selected?.status_last_known === "running") {
        setJobStartedAtMs(Date.now());
        setJobFinishedAtMs(null);
      } else if (selected) {
        const now = Date.now();
        setJobStartedAtMs(now);
        setJobFinishedAtMs(now);
      }
    },
    [resetViewState, selectionMode, draftId, clearSWRLocalViews, setLastJobId, select, jobId],
  );

  const onSelectDraft = React.useCallback(
    async (value: string) => {
      const parsedDraft = Number(value);
      if (!Number.isFinite(parsedDraft) || parsedDraft <= 0 || parsedDraft === draftId) return;

      resetViewState();
      if (selectionMode !== "draft") setSelectionMode("draft");
      if (jobId !== null) setJobId(null);
      setJobStartedAtMs(null);
      setJobFinishedAtMs(null);
      await clearSWRLocalViews();

      setDraftId(parsedDraft);

      const item = selectDraft(parsedDraft);
      if (item?.job_id && item.job_id !== lastJobId) setLastJobId(item.job_id);
    },
    [resetViewState, selectionMode, jobId, draftId, clearSWRLocalViews, selectDraft, setLastJobId, lastJobId],
  );

  const clearSelection = React.useCallback(async () => {
    if (jobId !== null) setJobId(null);
    if (draftId !== null) setDraftId(null);
    if (selectionMode !== "job") setSelectionMode("job");
    resetViewState();
    lastAutoOpenKeyRef.current = null;
    setJobStartedAtMs(null);
    setJobFinishedAtMs(null);
    await clearSWRLocalViews();
  }, [jobId, draftId, selectionMode, resetViewState, clearSWRLocalViews]);

  const openDebug = React.useCallback(
    (tab: DebugTab = "status") => {
      setActiveDebugTab(tab);
      if (DEBUG_ENABLED) setIsDebugOpen(true);
    },
    [setActiveDebugTab],
  );

  const handleCopyJobId = React.useCallback(async () => {
    if (!jobId) return;

    try {
      if (typeof navigator === "undefined" || !navigator.clipboard) {
        throw new Error("Clipboard indisponible");
      }

      await navigator.clipboard.writeText(jobId);
      toast.success(`Copié: ${jobId}`);
    } catch {
      toast.error("Impossible de copier l'ID job");
    }
  }, [jobId]);

  const scrollToPlanning = React.useCallback(() => {
    planningSectionRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
  }, []);

  React.useEffect(() => {
    if (!DEBUG_ENABLED || isDebugOpen || currentErrorKey === null) return;
    if (currentErrorKey === lastAutoOpenKeyRef.current) return;

    setActiveDebugTab("errors");
    setIsDebugOpen(true);
    lastAutoOpenKeyRef.current = currentErrorKey;
  }, [isDebugOpen, currentErrorKey]);

  return (
    <div className="space-y-6 p-4 md:p-6">
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between gap-3">
            <CardTitle>Génération automatique de planning équipe</CardTitle>
            {DEBUG_ENABLED ? (
              <Button variant="ghost" size="sm" onClick={() => openDebug("status")}>
                Debug
              </Button>
            ) : null}
          </div>
          <CardDescription>Lance une génération asynchrone, suit le job puis affiche le draft généré.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
            <div className="space-y-2">
              <Label>Équipe</Label>
              <TeamHeaderSelect teams={teams} valueId={teamId} onChange={setTeamId} />
            </div>

            <div className="space-y-2">
              <Label>Période</Label>
              <PlanningPeriodControls
                value={period}
                onChange={setPeriod}
                onPrev={() => setPeriod((p) => shiftPlanningPeriod(p, -1))}
                onNext={() => setPeriod((p) => shiftPlanningPeriod(p, 1))}
              />
            </div>
          </div>

          <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="seed">Seed</Label>
              <Input id="seed" type="number" value={seed} onChange={(e) => setSeed(Number(e.target.value))} />
            </div>

            <div className="space-y-2">
              <Label htmlFor="time-limit">Time limit (secondes)</Label>
              <Input
                id="time-limit"
                type="number"
                min={1}
                value={timeLimitSeconds}
                onChange={(e) => setTimeLimitSeconds(Number(e.target.value))}
              />
            </div>
          </div>

          {isPeriodInvalid ? (
            <Alert variant="destructive">
              <AlertTitle>Période invalide</AlertTitle>
              <AlertDescription>La date de début doit être antérieure ou égale à la date de fin.</AlertDescription>
            </Alert>
          ) : null}

          <div className="space-y-2">
            <Button onClick={handleGenerate} disabled={!canGenerate}>
              {isBusy ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  génération en cours
                </>
              ) : (
                "Lancer génération"
              )}
            </Button>

            {!canGenerate ? (
              <p className="text-xs text-muted-foreground">
                {teamId === null
                  ? "Sélectionnez une équipe pour lancer la génération."
                  : isPeriodInvalid
                    ? "Corrigez la période avant de lancer la génération."
                    : "Une génération est déjà en cours (queued/running)."}
              </p>
            ) : null}
          </div>

          {showConflictAlert ? (
            <Alert>
              <AlertTitle>Une génération est déjà en cours.</AlertTitle>
              <AlertDescription>
                {jobId || lastJobId
                  ? "Reprise du polling sur le job connu."
                  : "Aucun job connu. Sélectionnez un job récent dans l’historique si vous ne connaissez pas le job en cours."}
              </AlertDescription>
            </Alert>
          ) : null}

          {generate.error && !(generate.error instanceof ApiError && generate.error.status === 409) ? (
            <Alert variant="destructive">
              <AlertTitle>Erreur génération</AlertTitle>
              <AlertDescription>{generate.error.message}</AlertDescription>
            </Alert>
          ) : null}
        </CardContent>
      </Card>

      {shouldShowStatusBar ? (
        <JobStatusBar
          status={status}
          jobId={jobId}
          draftId={draftId}
          isBusy={isRunning}
          hasError={hasError}
          debugEnabled={DEBUG_ENABLED}
          debugIndicator={debugIndicator}
          startedAtMs={jobStartedAtMs}
          finishedAtMs={jobFinishedAtMs}
          onCopyJobId={() => void handleCopyJobId()}
          onRefresh={() => void job.mutate()}
          onOpenDebug={DEBUG_ENABLED ? openDebug : undefined}
          onScrollToPlanning={status === "success" && draftId ? scrollToPlanning : undefined}
          helperText={selectionMode === "job" ? "Mode: Job actif" : "Mode: Draft sélectionné"}
        />
      ) : null}

      {job.error ? (
        <Alert variant="destructive">
          <AlertTitle>Erreur statut job</AlertTitle>
          <AlertDescription>{job.error.message}</AlertDescription>
        </Alert>
      ) : null}

      {draftNotFound ? (
        <Alert variant="destructive">
          <AlertTitle>Draft introuvable (supprimé / non créé)</AlertTitle>
          <AlertDescription className="space-y-3">
            <p>Le planning du draft n&apos;est pas disponible.</p>
            <Button variant="outline" size="sm" onClick={() => void job.mutate()}>
              Recharger statut du job
            </Button>
          </AlertDescription>
        </Alert>
      ) : null}

      <div ref={planningSectionRef}>
        <Card>
          <CardHeader>
            <CardTitle>Planning du draft</CardTitle>
          </CardHeader>
          <CardContent>
            {!draftId ? (
              <p className="text-sm text-muted-foreground">Aucun draft sélectionné.</p>
            ) : draft.isLoading ? (
              <div className="flex items-center gap-2 text-sm text-muted-foreground">
                <Loader2 className="h-4 w-4 animate-spin" />
                Chargement du planning draft…
              </div>
            ) : planningVm ? (
              <TeamPlanningMatrix days={planningVm.days} rows={planningVm.rows} readOnly />
            ) : (
              <p className="text-sm text-muted-foreground">Aucune donnée de planning à afficher.</p>
            )}
          </CardContent>
        </Card>
      </div>

      {DEBUG_ENABLED ? (
        <TeamAutoGenerateDebugSheet
          open={isDebugOpen}
          onOpenChange={setIsDebugOpen}
          selectionMode={selectionMode}
          jobId={jobId}
          draftId={draftId}
          activeTab={activeDebugTab}
          onTabChange={setActiveDebugTab}
          status={status}
          jobData={job.data}
          jobError={job.error}
          draftError={draft.error}
          draftNotFound={draftNotFound}
          showConflictAlert={showConflictAlert}
          requestPayload={lastRequestPayload}
          history={history}
          jobSelectValue={jobSelectValue}
          draftSelectValue={draftSelectValue}
          onSelectJob={onSelectJob}
          onSelectDraft={onSelectDraft}
          onRefreshStatus={() => void job.mutate()}
          onReset={() => void clearSelection()}
          onClearHistory={clear}
        />
      ) : null}
    </div>
  );
}
