from __future__ import annotations
from datetime import date
from typing import List, Optional, Protocol, runtime_checkable
from core.domain.entities.affectation import Affectation


@runtime_checkable
class AffectationRepositoryPort(Protocol):
    def get_for_agent_and_day(self, agent_id: int, jour: date) -> Optional[Affectation]: ...
    def list_all(self) -> List[Affectation]: ...
    def list_for_agent(self, agent_id: int) -> List[Affectation]: ...
    def list_for_day(self, jour: date) -> List[Affectation]: ...
    def list_for_poste(self, poste_id: int, start: Optional[date], end: Optional[date]) -> List[Affectation]: ...