from __future__ import annotations
from typing import List, Optional, Protocol, runtime_checkable
from core.domain.entities.agent import Agent


@runtime_checkable
class AgentRepositoryPort(Protocol):
    def count(self) -> int: ...
    def create(self, entity: Agent) -> Agent: ...
    def delete(self, object_id: int) -> bool: ...
    def exists_for_regime(self, regime_id: int) -> bool: ...
    def get_by_id(self, agent_id: int) -> Optional[Agent]: ...
    def list(self, *, limit: Optional[int] = None, offset: int = 0) -> List[Agent]: ...
    def list_all(self) -> List[Agent]: ...
    def list_by_regime_id(self, regime_id: int) -> List[Agent]: ...
    def set_active(self, agent_id: int, is_active: bool) -> bool: ...
    def update(self, entity: Agent) -> Optional[Agent]: ...