from datetime import date
from typing import List, Protocol

from core.domain.entities import AgentDayAssignment


class AgentDayAssignmentRepositoryPort(Protocol):
    def create(self, entity: AgentDayAssignment) -> AgentDayAssignment: ...
    def delete_by_agent_day_id(self, agent_day_id: int) -> bool: ...
    def delete_by_date_and_tranche_ids(self, day_date: date, tranche_ids: List[int]) -> bool: ...
    def exists_for_tranche(self, tranche_id: int) -> bool: ...