# core/application/ports/agent_day_repository.py
from __future__ import annotations
from datetime import date
from typing import Protocol, List, Optional

from core.domain.entities.agent_day import AgentDay


class AgentDayRepositoryPort(Protocol):
    def exists_for_agent(self, agent_id: int) -> bool:...
    def get_by_agent_and_date(self, agent_id: int, day_date: date) -> Optional[AgentDay]:...
    def list_by_agent_and_range(self, agent_id: int, start_date: date, end_date: date) -> List[AgentDay]:...
    def list_by_poste_and_range(self, poste_id: int, start_date: date, end_date: date) -> List[AgentDay]: ...