from __future__ import annotations
from typing import List, Optional, Protocol, runtime_checkable

from core.domain.entities.agent_team import AgentTeam

@runtime_checkable
class AgentTeamRepositoryPort(Protocol):
    def create(self, entity: AgentTeam) -> AgentTeam: ...
    def delete_for_agent_and_team(self, *, agent_id: int, team_id: int) -> bool: ...
    def exists_agent(self, agent_id: int) -> bool: ...
    def exists_team(self, team_id: int) -> bool: ...
    def get_for_agent_and_team(self, *, agent_id: int, team_id: int) -> Optional[AgentTeam]: ...
    def search(self, agent_id: Optional[int] = None, team_id: Optional[int] = None) -> List[AgentTeam]: ...