from __future__ import annotations
from datetime import date
from typing import List, Optional, Protocol, runtime_checkable
from core.domain.entities.etat_jour_agent import EtatJourAgent


@runtime_checkable
class EtatJourAgentRepositoryPort(Protocol):
    def get_for_agent_and_day(self, agent_id: int, jour: date) -> Optional[EtatJourAgent]: ...
    def list_all(self) -> List[EtatJourAgent]: ...
    def list_between_dates(self, date_start: date, date_end: date) -> List[EtatJourAgent]: ...
    def list_for_agent(self, agent_id: int) -> List[EtatJourAgent]: ...
    def list_for_agent_between_dates(self, agent_id: int, date_start: date, date_end: date) -> List[EtatJourAgent]: ...
