from __future__ import annotations
from typing import List, Optional, Protocol, runtime_checkable
from core.domain.entities.poste import Poste


@runtime_checkable
class PosteRepositoryPort(Protocol):
    def count(self) -> int: ...
    def create(self, entity: Poste) -> Poste: ...
    def delete(self, object_id: int) -> bool: ...
    def get_by_id(self, poste_id: int) -> Optional[Poste]: ...
    def list(self, *, limit: Optional[int] = None, offset: int = 0) -> List[Poste]: ...
    def list_all(self) -> List[Poste]: ...
    def update(self, entity: Poste) -> Optional[Poste]: ...