from __future__ import annotations
from typing import List, Optional, Protocol, runtime_checkable
from core.domain.entities.qualification import Qualification


@runtime_checkable
class QualificationRepositoryPort(Protocol):
    def create(self, entity: Qualification) -> Qualification: ...
    def delete_for_agent_and_poste(self, agent_id: int, poste_id: int) -> bool: ...
    def get_for_agent_and_poste(self, agent_id: int, poste_id: int) -> Optional[Qualification]: ...
    def is_qualified(self, agent_id: int, poste_id: int) -> bool: ...
    def list_all(self) -> List[Qualification]: ...
    def list_for_agent(self, agent_id: int) -> List[Qualification]: ...
    def list_for_poste(self, poste_id: int) -> List[Qualification]: ...
    def search(self, agent_id: Optional[int] = None, poste_id: Optional[int] = None) -> List[Qualification]: ...
    def update(self, entity: Qualification) -> Optional[Qualification]: ...