from __future__ import annotations
from datetime import datetime
from typing import Optional, Protocol
from typing_extensions import runtime_checkable
from db.models.refresh_token import RefreshToken

@runtime_checkable
class RefreshTokenRepositoryPort(Protocol):
    def add(self, token: RefreshToken) -> None: ...
    def commit(self) -> None: ...
    def get_by_hash(self, token_hash: str) -> Optional[RefreshToken]: ...
    def get_user_id_by_hash(self, token_hash: str) -> Optional[int]: ...
    def revoke(self, token: RefreshToken, now: datetime) -> None: ...
    def revoke_by_hash_if_active(self, token_hash: str, now: datetime) -> bool: ...
    def revoke_all_for_user(self, user_id: int, now: datetime) -> int: ...
