from __future__ import annotations
from typing import List, Optional, Protocol, runtime_checkable
from core.domain.entities.regime import Regime


@runtime_checkable
class RegimeRepositoryPort(Protocol):
    def count(self) -> int: ...
    def get_by_id(self, regime_id: int) -> Optional[Regime]: ...
    def list(self, *, limit: Optional[int] = None, offset: int = 0) -> List[Regime]: ...
    def list_all(self) -> List[Regime]: ...
