from __future__ import annotations
from typing import List, Optional, Protocol, runtime_checkable

from core.domain.entities.team import Team

@runtime_checkable
class TeamRepositoryPort(Protocol):
    def count(self) -> int: ...
    def create(self, entity: Team) -> Team: ...
    def update(self, entity: Team) -> Optional[Team]: ...
    def delete(self, object_id: int) -> bool: ...
    def get_by_id(self, team_id: int) -> Optional[Team]: ...
    def get_by_name(self, name: str) -> Optional[Team]: ...
    def list(self, *, limit: Optional[int] = None, offset: int = 0) -> List[Team]: ...
    def list_agent_ids(self, team_id: int) -> List[int]: ...
    def list_all(self) -> List[Team]: ...
    def get_existing_ids(self, team_ids: set[int]) -> set[int]: ...