from __future__ import annotations
from typing import List, Optional, Protocol, runtime_checkable
from core.domain.entities.tranche import Tranche


@runtime_checkable
class TrancheRepositoryPort(Protocol):
    def count(self) -> int: ...
    def create(self, entity: Tranche) -> Tranche: ...
    def delete(self, object_id: int) -> bool: ...
    def exists_for_poste(self, poste_id: int) -> bool: ...
    def get_by_id(self, tranche_id: int) -> Optional[Tranche]: ...
    def list(self, *, limit: Optional[int] = None, offset: int = 0) -> List[Tranche]: ...
    def list_all(self) -> List[Tranche]: ...
    def list_by_ids(self, ids: List[int]) -> List[Tranche]:...
    def list_by_poste_id(self, poste_id: int) -> List[Tranche]: ...
    def update(self, entity: Tranche) -> Optional[Tranche]: ...
